- name: Configuring Redis Repository
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo 

- name: Installing Redis 
  ansible.builtin.package:
    name: redis-6.2.13
    state: present  

- name: Updating the Redis Config to be public
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0' 

- name: Starting redis 
  ansible.builtin.systemd:
    name: redis 
    state: started
    enabled: true 

- name: Configuring Node Name 
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}